maskinporten:
  wellknown: https://ver2.maskinporten.no/
  client-id:
  scope: folkeregister:deling/offentligmedhjemmel
  kid:
  jwks:

freg:
  base-url: https://folkeregisteret-api-konsument.sits.no
  sequence: /folkeregisteret/offentlig-med-hjemmel/api/v1/hendelser/siste/sekvensnummer
  feed: /folkeregisteret/offentlig-med-hjemmel/api/v1/hendelser/feed
  person: /folkeregisteret/offentlig-med-hjemmel/api/v1/personer/{personNin}
  event-document: /folkeregisteret/offentlig-med-hjemmel/api/v1/hendelser/{id}

events:
  include: CHANGE_IN_NAME

logging:
  level:
    org.springframework.r2dbc: INFO
    # org.springframework.r2dbc: DEBUG